# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94fd6c71d697bf7bd6bb43ca6b09e7db20304c069a5413fa9611c210f1262cf5da140524a6bde4e640056291f71320eea658c204aa94ce79550a3d3179f5ef5c

test:
  secret_key_base: 96dfb0d1bd4dff4f56cd6e78b68c1eae40a28717121a43a22b34cc13e44f3a901388d0b78f0ee658e11972770b357b0b46492ff8e6500ecfb57691a795fa039e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
